# Generated by Django 6.0.3 on 2026-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manager', 'manager'), ('landlord', 'landlord'), ('realtor', 'realtor'), ('tenant', 'tenant')], max_length=50, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
