# Generated by Django 6.0.3 on 2026-03-28 23:25

from django.db import migrations

# Generated by Django 6.0.3 on 2026-03-28 23:19

from django.db import migrations


def create_roles(apps, schema_editor):
    Rol = apps.get_model('rol','Rol')

    roles = ['admin','user']

    for role in roles:
        Rol.objects.get_or_create(name=role)


def delete_roles(apps, schema_editor):
    Rol = apps.get_model('rol', 'Rol')
    Rol.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, delete_roles),
    ]
