# Generated by Django 6.0.3 on 2026-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=50, unique=True),
        ),
    ]
